bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: "Carlos Avenda\xF1o"
  description: nextflow pipeline workflow for ase data generate
  force: true
  is_nfcore: true
  name: easyase
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0dev
update: null
