contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #easyase channel"
    url: https://nfcore.slack.com/channels/easyase
    about: Discussion about the nf-core/easyase pipeline
